### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by cruduxcru0** [cruduxcru0/WTFweg#1]
- [ ]  ZIP/RAR/7z reading
- [ ] Deflate/LZMA/LZ4 compression
- [ ] CHD/BIN+CUE+MP3+FLAC+Vorbis+WavPack/ISO etc reading for CD VFS/CD mounting
- [ ] MIDI synthesis
- [ ] Write self contained WASAPI audio playback
- [ ] Unique input descriptor serialization
- [ ] Rewrite configuration system (JSON?)
- [ ] Finalize keyboard/mouse support
- [ ] Subsystems
- [ ] Post process audio filters & video shaders/filters
